### ISSUE TITLE
Menu notifications

### ISSUE THREAD

**Issue by Siegrift** [api3dao/api3-dao-dashboard#137]
New change in the design is to show a badge in the "governance" section with a number of active proposals since last logged in.

This is a nice UX feature, but complex as we will need:
- Persist when the user last logged in in localstorage
- Don't display it for the first time user (upon first ever login)
- Update it when he clicks the proposals tab (to hide the badges)
- Implement the UI part

**Comment by bbenligiray** [comment]
We don't fetch the proposals until governance is clicked, so this would require how things work to change bigly
