### ISSUE TITLE
Allow ENS names in delegation address field

### ISSUE THREAD

**Issue by Siegrift** [api3dao/api3-dao-dashboard#203]
Based on https://api3workspace.slack.com/archives/C020RCCC3EJ/p1625678335010000

We can use ethers to resolve a name which will make it easier for people to delegate (if the delegate uses ENS name)

**Comment by bbenligiray** [comment]
We should also attempt to [look up](https://docs.ethers.io/v5/api/providers/provider/#Provider-lookupAddress):
- Current delegate for the user
- Proposal creator
