### ISSUE TITLE
Show epoch information

### ISSUE THREAD

**Issue by dcroote** [api3dao/api3-dao-dashboard#207]
There have been similar questions in Telegram and Discord (e.g. [this exchange](https://discord.com/channels/758003776174030948/789873269015707738/863884272435986443)) regarding when staking rewards are distributed.

Consequently, might it be valuable to show epoch information like current epoch and/or a countdown until the next epoch?

**Comment by Siegrift** [comment]
Hi, there is great open source tool https://enormous.cloud/dao/api3/tracker/ which allows you to see this and many other things we do not support natively (mostly to keep the dashboard app as minimal as possible).
