### ISSUE TITLE
Update APY and inflation rate

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/api3-dao-dashboard#208]
The displayed APY is estimated, assuming the APR will remain constant for a whole year (which won't happen). This needs to be clarified with a tooltip.

"Annual inflation rate" is not the correct term, should be "Annual total supply growth". This is also dependent on the APR remaining constant for a whole year. A tooltip must clarify this.

The annual total supply growth is wrong here
https://github.com/api3dao/api3-dao-dashboard/blob/227b67c121cdeb00e88f30dad21dc1c7fabcaaf5/src/contracts/helpers.ts#L25
should be
```ts
return (annualMintedTokens.mul(precision).div(totalSupply).toNumber() / precision) * 100;
```
instead

**Comment by Siegrift** [comment]
Do I understand correctly?
1. Add tooltips to both "Annual rewards" and "annual supply growth"? Can It say "Annual rewards is estimated and may change in time"
2. Change the calculation and label of "Annual inflation rate". This also mean that calculation is wrong. Should I stop linking that g-doc in the code? https://docs.google.com/document/d/1ESEkemgFOhP5_tXajhuy5Mozdm8EwU1O2YSKSBwnrUQ/edit

**Comment by bbenligiray** [comment]
1. Yes. I think both tooltips should read "Value is extrapolated based on the current APR". Alternatively, we can add an * to both (Annual Rewards (APY)* and Annual Growth Rate*) and add this as a line below Annual Inflation Rate, but that may be difficult to style.
2. Correct. Keep the link for now, it's probably useful. I'll update the doc.
