### ISSUE TITLE
Missing the Rinkeby deployment

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/api3-dao-dashboard#214]
I think it's useful to keep a Rinkeby version of the DAO up. Creating this issue as a TODO note.

**Comment by Siegrift** [comment]
What is this issue about? The rinkeby version is still running and the addresses are in https://github.com/api3dao/api3-dao-dashboard/blob/main/src/contract-deployments/rinkeby-dao.json

**Comment by bbenligiray** [comment]
Never mind, I forgot that the same deployment served both mainnet and Rinkeby
