### ISSUE TITLE
Replace dao.api3.org with api3dao.org

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/api3-dao-dashboard#216]
We may want to use `api3dao.org` instead of `dao.api3.org`, leaving this here as a TODO item for the lack of a better place

**Comment by Siegrift** [comment]
@bbenligiray Is this still actionable? I remember there was a slack thread where @andreogle disliked this and I am not fond of changing it either.

**Comment by bbenligiray** [comment]
I created a more general version on the common tasks Jira board, this can be closed
