### ISSUE TITLE
Proposal option radio button should select the Secondary option by default 

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/api3-dao-dashboard#255]
Most proposals are of secondary type so this would prevent errors such as https://api3.eth.link/#/governance/primary-0

**Comment by Siegrift** [comment]
The following should be changed https://github.com/api3dao/api3-dao-dashboard/blob/main/src/pages/proposals/forms/new-proposal-form.tsx#L45

**Comment by bbenligiray** [comment]
This still defaults to primary for me. I assume the fix should have been released.

**Comment by Siegrift** [comment]
Yeah, it was merged only to `main`, but not released to production.

**Comment by bbenligiray** [comment]
New proposals on both api3.eth.limo and dao.api3.org default to secondary at the moment :thinking:

**Comment by dcroote** [comment]
> New proposals on both api3.eth.limo and dao.api3.org default to secondary at the moment 🤔

Ah right, this was ported to production on 07DEC [here](https://github.com/api3dao/api3-dao-dashboard/commit/fcf4f613597ad97891acd46063334ab96b113ff0). Well... can't blame the dashboard for selecting primary then 😓
