### ISSUE TITLE
Voting on proposals should be blocked after first vote from same user

### ISSUE THREAD

**Issue by LikeTheJar** [api3dao/api3-dao-dashboard#266]
When submitting a proposal, the submitter automatically has a vote cast.  The DAO Dashboard allows the user to submit a second vote, and while it doesn't count two votes from the same user it still charges for gas and allows for the execution of that vote.  Please implement a blocker to keep end users from accidentally executing a second vote so that they are not charged gas fees for a transaction that won't go through.

**Comment by bbenligiray** [comment]
This is probably fixed along the way
