### ISSUE TITLE
Chunk proposal loading

### ISSUE THREAD

**Issue by Siegrift** [api3dao/api3-dao-dashboard#287]
Currently, we are fetching proposals at once. This is taking too long for history proposals and we should fetch them in chunk (as originally planned).

This issue should resolve the following TODO items:
* https://github.com/api3dao/api3-dao-dashboard/blob/ca4be1112c546aee129ba8e4c65da98e8cab42fc/src/logic/proposals/hooks/history-proposals.ts#L42
* https://github.com/api3dao/api3-dao-dashboard/blob/ca4be1112c546aee129ba8e4c65da98e8cab42fc/src/logic/proposals/hooks/history-proposals.ts#L112
* https://github.com/api3dao/api3-dao-dashboard/blob/ca4be1112c546aee129ba8e4c65da98e8cab42fc/src/logic/proposals/hooks/active-proposals.ts#L52

The last two are probably not that urgent, but it would be nice to chunk them as well.

Relates to https://github.com/api3dao/api3-dao-dashboard/issues/77

**Comment by bbenligiray** [comment]
One thing that is sort of related is that the user can't tell when the dashboard is loading something from the chain

**Comment by Siegrift** [comment]
Yeah, that is tracked here: https://github.com/api3dao/api3-dao-dashboard/issues/254

**Comment by mcoetzee** [comment]
Loading performance has been fixed in https://github.com/api3dao/api3-dao-dashboard/pull/370. The PR was merged into the dev branch, and is planned to land along with the claims feature.
