### ISSUE TITLE
Calculating taxes reports

### ISSUE THREAD

**Issue by musinit** [api3dao/api3-dao-dashboard#358]
What if every member of DAO could calculate his capital gains/losses or income to send taxes reports? Today people need to use some 3-rd party service like Cointracker, but it's not Open Source. 
We can do it in an Open Source way, so there would be no need to pay for cointracker.com, cointracking.com, and other companies that do the same thing.
We can choose TOP 3 countries for a start.

**Comment by bbenligiray** [comment]
You can use https://enormous.cloud/dao/api3/tracker/wallets/YOUR_ADDRESS to see your individual reward payments. The implementation is open source https://github.com/EnormousCloud/api3-dao-tracker We don't consider country-specific tax calculations within the scope of our project (as in, we won't dedicate funds/resources to it), but we welcome community contributions.

**Comment by musinit** [comment]
What if we add the ability to calculate capital gains/losses and incomes for your rewards? So people can see the taxable amount in dollars (or other currencies)
I am a crypto tax fan and I can think about this and contribute. I also have tax professional with me. But at first I need to speak with maintainers to discuss the details.

**Comment by bbenligiray** [comment]
We have since started supporting https://tracker.api3.org/ officially. We're not planning to do anything further about this.
