### ISSUE TITLE
My withdrawable balance is not correct

### ISSUE THREAD

**Issue by yiucp718** [api3dao/api3-dao-dashboard#437]
I used to stake my api3 to the protocol. I have initiated unstake and waited for more than 7 days. yet my withdrawable balance does not include the staking rewards

can someone help? thanks

**Comment by bbenligiray** [comment]
Hi @yiucp718 , I suspect that this is because the [staking rewards become withdrawable after a year](https://docs.api3.org/guides/dao-members/staking.html#unstake-and-claim). If you share your Ethereum address we can confirm if that's the reason.

**Comment by yiucp718** [comment]
hi @bbenligiray,
thanks, I'm not aware of the fact that staking rewards are only withdrawable after a year... must've missed that section in the manual...
