### ISSUE TITLE
Address the delay when displaying Proposal History

### ISSUE THREAD

**Issue by PrenaamD** [api3dao/api3-dao-dashboard#448]
As reported in this [Slack post](https://api3workspace.slack.com/archives/C02ALA11APM/p1715974438994919)

> if you connect your wallet in either staking or governance and then open the history page, you get a "there are no past proposals" message for more than 5 seconds in place of "loading"
> "loading" mainly appears when you reload the history page and then connect to your wallet

**Comment by bbenligiray** [comment]
This appears to be fixed
