### ISSUE TITLE
Rebrand DAO Dashboard - Colors & fonts

### ISSUE THREAD

**Issue by peterjurco** [api3dao/api3-dao-dashboard#454]
- Update CSS variables so they contain all the new colors used in the rebranded DAO dashboard. Use the same naming as in the Figma.
- Explore possibilities how to use the new font styles (either with TS like in the Market or with SCSS if possible). 
- Add the new font styles to the DAO Dashboard.
- Create new CSS variables for breakpoints that will be used in the new designs

**Comment by PrenaamD** [comment]
@peterjurco I don't think there are any visual changes to test here? Please let me know if otherwise.

**Comment by peterjurco** [comment]
Yes, no visual changes, just preparation for the visual changes
