### ISSUE TITLE
Rebrand DAO Dashboard - Staking page

### ISSUE THREAD

**Issue by peterjurco** [api3dao/api3-dao-dashboard#456]
Updates styles of the Staking page so it matches [new designs](https://www.figma.com/design/NG6QClnVrvPRZ5gJ3s0zen/%E2%9F%81--Api3-DAO---Branding-Update?node-id=8676-107801&node-type=section&m=dev). This includes
- Main section of the page (Layout to be done in separate task)
- Unconnected wallet state (we don't have updated video yet, leave the current one)
- Connected wallet state (and some tokens staked)
- Unstaking state

No modals should be updated in this task (Staking / Unstaking). 

![Image](https://github.com/user-attachments/assets/e7cb7c70-4dea-47db-9ec9-2edeed37324e)

**Comment by peterjurco** [comment]
@PrenaamD FYI

- Tooltips on the page will be done in the #487 
- You might have done it already but for local testing of staking / depositing, etc. you can use hardhat - check out [these intructions](https://github.com/api3dao/api3-dao-dashboard/blob/main/dev-README.md)

**Comment by Anboias** [comment]
It seems I'm not able to tag Prenaam, but also FYI after rebasing this branch to `rebrand` (it was previously based on @peterjurco's PR with the Layout), CI revealed some Cypress test failures. Working on fixing those, so I think it makes sense to put this back in progress until they're done.

**Comment by Anboias** [comment]
Fixed

**Comment by PrenaamD** [comment]
@Anboias 
Feedback 1
According to the design the "Unstake" and "Unstake and Withdraw" buttons have the same width. 
Implementation
![Image](https://github.com/user-attachments/assets/66e28d53-5985-4078-b1fb-08f1441b7d92)
Design
![Image](https://github.com/user-attachments/assets/cfcdf921-bb80-41d7-8174-154b362f9806)

**Comment by PrenaamD** [comment]
Feedback 2
After the cooldown period for unstaking, 
- the "unstake and Withdraw" button in the staking card doesn't work even though it appears enabled.  
- the "unstake and Withdraw" button at the top of the page works as expected

https://github.com/user-attachments/assets/04d853ab-3cb2-4a7a-a4f9-e2a284770b67

**Comment by Anboias** [comment]
Nice catches, @PrenaamD. Thanks.
Should be both fixed now
