### ISSUE TITLE
Rebrand DAO Dashboard - Proposals table

### ISSUE THREAD

**Issue by peterjurco** [api3dao/api3-dao-dashboard#461]
Update Proposals table based on the [new designs]. The table is used for active proposals on the Governance page and for past proposals on the History page. 

⚠️Do not add pagination to the table - contact @mcoetzee who already did some job on that.

(https://www.figma.com/design/NG6QClnVrvPRZ5gJ3s0zen/%E2%9F%81--Api3-DAO---Branding-Update?node-id=9057-88620&node-type=section&m=dev) 

![Image](https://github.com/user-attachments/assets/057988d5-2290-4d9e-b725-3adeaf431815)

**Comment by PrenaamD** [comment]
Thanks for the great testing instructions and dispositions. 🙏🏾
