### ISSUE TITLE
Rebrand DAO Dashboard - Governance page modals

### ISSUE THREAD

**Issue by peterjurco** [api3dao/api3-dao-dashboard#462]
Update delegation modals on the Governance page based on the [new designs](https://www.figma.com/design/NG6QClnVrvPRZ5gJ3s0zen/%E2%9F%81--Api3-DAO---Branding-Update?node-id=8676-108208&node-type=frame&m=dev)

![Image](https://github.com/user-attachments/assets/2d7ea36d-bea1-4ca5-bd4d-cd72a76f4a0e)

![Image](https://github.com/user-attachments/assets/5d8867e3-8e0b-47d3-b619-b27d77c2194d)

![Image](https://github.com/user-attachments/assets/20f9b392-8056-43cb-be79-32cd6b1c7123)

**Comment by PrenaamD** [comment]
@Anboias The implementation seems quite different from the design. Is the design outdated?
Implementation
![Image](https://github.com/user-attachments/assets/e2cf37c6-15fe-4bce-84bb-2c65c62e4dc6)


[designs](https://www.figma.com/design/NG6QClnVrvPRZ5gJ3s0zen/%E2%9F%81--Api3-DAO---Branding-Update?node-id=8676-108208&node-type=frame&m=dev)
![Image](https://github.com/user-attachments/assets/d6cf6fec-f395-46ae-be85-55e7d74305cd)

**Comment by peterjurco** [comment]
@PrenaamD 

There was discussion about this and they [changed](https://github.com/api3dao/tasks/issues/1535) the designs in the meantime. Let's merge this and I will update it as part of the #506. @Anboias are you ok with that?

**Comment by PrenaamD** [comment]
Thanks for letting me know. It is fine with me. Please feel free to merge it and close the issue.
