### ISSUE TITLE
Rebrand DAO Dashboard - Proposal Details

### ISSUE THREAD

**Issue by peterjurco** [api3dao/api3-dao-dashboard#463]
Update Proposal Details page based on the [new designs](https://www.figma.com/design/NG6QClnVrvPRZ5gJ3s0zen/%E2%9F%81--Api3-DAO---Branding-Update?node-id=8676-108155&node-type=frame&m=dev). This includes
- All states of the page (Unvoted / Voted for / Voted against / Wallet unconnected)
- All [breakpoints](https://www.figma.com/design/NG6QClnVrvPRZ5gJ3s0zen/%E2%9F%81--Api3-DAO---Branding-Update?node-id=9057-94529&node-type=section&m=dev)

![Image](https://github.com/user-attachments/assets/7f252fb9-41d3-4939-9fc7-05c6822812bc)

**Comment by PrenaamD** [comment]
@peterjurco 
In the implementation
- Creator field is present but missing from the [design](https://www.figma.com/design/NG6QClnVrvPRZ5gJ3s0zen/%E2%9F%81--Api3-DAO---Branding-Update?node-id=8676-108155&t=0mAsAvTswyL469mX-1)
- "Target Address" should be "Target contract address" according to the design
- The Value field is missing but present in the design

**Comment by peterjurco** [comment]
@PrenaamD 

I have updated "Target Address" to "Target Contract Address". Two other points will be updated in the designs ([task](https://github.com/api3dao/tasks/issues/1553)).
