### ISSUE TITLE
Rebrand DAO Dashboard - History page

### ISSUE THREAD

**Issue by peterjurco** [api3dao/api3-dao-dashboard#465]
Update designs of the History page based on the [new designs](https://www.figma.com/design/NG6QClnVrvPRZ5gJ3s0zen/%E2%9F%81--Api3-DAO---Branding-Update?node-id=8676-108295&node-type=section&m=dev)
Most of the components should be already done in previous tasks ([Proposals table](https://github.com/api3dao/api3-dao-dashboard/issues/461), [Proposal detail](https://github.com/api3dao/api3-dao-dashboard/issues/463)) but make sure all of the states are covered and it is working well on the History page.

![Image](https://github.com/user-attachments/assets/f97ed04a-0906-4cda-b85e-faaba211f392)

**Comment by PrenaamD** [comment]
@peterjurco can I assume that the History table is similar to the proposals table tested in #499 ?
If yes I can mark this issue as tested

**Comment by peterjurco** [comment]
@PrenaamD Yes, that's the same component. You can mark this tested
