### ISSUE TITLE
Rebrand DAO Dashboard - Unstake banner

### ISSUE THREAD

**Issue by Anboias** [api3dao/api3-dao-dashboard#486]
## Requirements

Update Unstake Banner from the Staking page. [Designs](https://www.figma.com/design/NG6QClnVrvPRZ5gJ3s0zen/%E2%9F%81--Api3-DAO---Branding-Update?node-id=8676-107954&node-type=frame&m=dev)

![Image](https://github.com/user-attachments/assets/c66993a0-9065-4b57-a2a7-b2d497a4b71f)

**Comment by PrenaamD** [comment]
@peterjurco 
"Unstake within {days} and {hours}" present in the [design](https://www.figma.com/design/NG6QClnVrvPRZ5gJ3s0zen/%E2%9F%81--Api3-DAO---Branding-Update?node-id=8676-107954&t=7OIlgeSFYTnUTLCz-1) is missing from the implementation.
Not sure if it also requires a logic change.

**Comment by peterjurco** [comment]
@PrenaamD Yeah, this isn't in the implementation. I don't know why there should be a time limit for unstaking, I don't see any logic for this implemented or even hinted in the repo.

**Comment by PrenaamD** [comment]
Yes. I don't know if there is a staking time limit. I'll report it to the Design team. If needed, this can be revisited in a separate issue.
