### ISSUE TITLE
Rebrand DAO Dashboard - Tooltips

### ISSUE THREAD

**Issue by Anboias** [api3dao/api3-dao-dashboard#487]
## Requirements
Update tooltips to [new branding](https://www.figma.com/design/BhnOcskTIGPZ18JkhbCuNQ/%E2%9F%81--Api3-DS---Branding-Update?node-id=1066-6887&m=dev)

<img width="360" alt="image" src="https://github.com/user-attachments/assets/7a46aaa6-f8e1-46ba-998b-3df653b9525c">

**Comment by PrenaamD** [comment]
This one is tested and ready to go
